from .example_node_1 import NODE_CLASS_MAPPINGS as NCM1
from .example_node_2 import NODE_CLASS_MAPPINGS as NCM2
from .example_node_1 import NODE_DISPLAY_NAME_MAPPINGS as NDMP1
from .example_node_2 import NODE_DISPLAY_NAME_MAPPINGS as NDMP2


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(NCM1)
NODE_CLASS_MAPPINGS.update(NCM2)

NODE_DISPLAY_NAME_MAPPINGS.update(NDMP1)
NODE_DISPLAY_NAME_MAPPINGS.update(NDMP2)
